version: '2'

services:
  database:
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test

  keycloak:
    image: jboss/keycloak:9.0.0
    volumes:
      - ./quarkus_realm.json:/tmp/quarkus_realm.json
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/quarkus_realm.json
