apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f ./infrastructure/docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
  namespace: quarkus-universal-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert -f ./infrastructure/docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - env:
            - name: KEYCLOAK_IMPORT
              value: /tmp/quarkus_realm.json
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_USER
              value: admin
          image: jboss/keycloak:9.0.0
          name: keycloak
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /tmp/quarkus_realm.json
              name: keycloak-realm
      restartPolicy: Always
      volumes:
        - name: keycloak-realm
          configMap:
            name: quarkus-realm
status: {}
