name: Build

on:
  push:
    branches:
      - master

jobs:

  build_java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 11
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk11'
      - name: Build Spring Application
        run: mvn -B clean verify -f spring/pom.xml
      - name: Build Quarkus Application
        run: mvn -B clean verify -Pnative -Dquarkus.native.container-build=true -f quarkus/pom.xml  
