name: Build

on:
  push:
    branches:
      - master

jobs:

  build-jvm:
    name: Build with Java ${{ matrix.java.version }} (OpenJDK)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '11', opts: '' },
          { 'version': '16', opts: '' },
          { 'version': '17', opts: '' }
        ]
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-java-${{ matrix.java.version }}
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
      - name: Build Spring Application
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: mvn -B clean verify -f spring/pom.xml -DskipTests
      - name: Build Quarkus Spring Application
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: mvn -B clean verify -f quarkus-spring/pom.xml
      - name: Build Quarkus Application
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: mvn -B clean verify -f quarkus/pom.xml

  build-native:
    name: Build native applications
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-java-11
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        name: set up jdk 11
        with:
          distribution: temurin
          java-version: 11
      - name: Build Quarkus Spring Application
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: mvn -B clean verify -Pnative -Dquarkus.native.container-build=true -f quarkus-spring/pom.xml
      - name: Build Quarkus Application
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: mvn -B clean verify -Pnative -Dquarkus.native.container-build=true -f quarkus/pom.xml




